pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Install Dependencies') {
            steps {
                // Install pytest and other requirements from the repo
                sh 'pip3 install --user -r requirements.txt'
            }
        }
        stage('Build') {
            steps {
                sh 'python3 -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            steps {
                // sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
                // Change 'py.test' to 'python3 -m pytest'
                sh 'python3 -m pytest --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}
